Updates examples from 3.2.3 to latest nightly
Emzi0767/DSharpPlus-Example-Bot pull request #6
Opened 2020-10-01 19:06 UTC by Kiritsu

As discussed, VB examples were dropped.

2020-10-01 19:14 UTC, Emzi0767 requested changes
Can you perhaps delete the .idea folder altogether? Overall seems good.

2020-10-01 19:15 UTC, Emzi0767 commented
I will be merging this as soon as 4.0 hits RC, which should be not long from now.

2020-10-02 18:32 UTC, Kiritsu commented
.idea folder was removed. I'll keep the example up to date here (with possible breaking changes) until RC1 is out.

2020-11-14 20:37 UTC, Emzi0767 approved these changes

2020-11-14 20:37 UTC, merged